name: build-openlane
on:
  push:
  workflow_dispatch:
jobs:
  build-openlane-sky130:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    env:
      REPO : subservient
      VLNV : subservient
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          path: subservient
      - uses: conda-incubator/setup-miniconda@v2
        with:
          installer-url: https://github.com/proppy/conda-eda/releases/download/v0.0-1358-g4ea08b3-40-g8227f29-1-g1007cd2-1-ga1cffe6/openlane-sky130a-0-Linux-x86_64.sh
          activate-environment: silicon-env
      - name: build with fusesoc
        run: |
          pip3 install fusesoc
          fusesoc library add serv https://github.com/olofk/serv
          fusesoc library add $REPO $GITHUB_WORKSPACE/$REPO
          fusesoc run --target=sky130 $VLNV
  build-openlane-gf180:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    env:
      REPO : subservient
      VLNV : subservient
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          path: subservient
      - uses: conda-incubator/setup-miniconda@v2
        with:
          installer-url: https://github.com/proppy/conda-eda/releases/download/v0.0-1358-g4ea08b3-40-g8227f29-1-g1007cd2-1-ga1cffe6/openlane-gf180mcuc-0-Linux-x86_64.sh
          activate-environment: silicon-env
      - name: build with fusesoc
        run: |
          pip3 install fusesoc
          fusesoc library add serv https://github.com/olofk/serv
          fusesoc library add $REPO $GITHUB_WORKSPACE/$REPO
          fusesoc run --target=gf180 $VLNV
