name: build-openlane
on:
  push:
  workflow_dispatch:
jobs:
  build-openlane-sky130:
    runs-on: ubuntu-latest
    env:
      REPO: subservient
      VLNV: subservient
      EDALIZE_LAUNCHER: /home/runner/work/subservient/subservient/subservient/el_conda_eda
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          path: subservient
      - uses: conda-incubator/setup-miniconda@v2
        with:
          installer-url: https://github.com/proppy/conda-eda/releases/download/v0.0-1403-ga3008a5/openlane-sky130a-0-Linux-x86_64.sh
          activate-environment: conda-eda
      - name: build with fusesoc
        shell: bash -l {0}
        run: |
          pip3 install fusesoc
          fusesoc library add serv https://github.com/olofk/serv
          fusesoc library add $REPO $GITHUB_WORKSPACE/$REPO
          fusesoc run --target=sky130 $VLNV
  build-openlane-gf180:
    runs-on: ubuntu-latest
    env:
      REPO: subservient
      VLNV: subservient
      EDALIZE_LAUNCHER: /home/runner/work/subservient/subservient/subservient/el_conda_eda
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          path: subservient
      - uses: conda-incubator/setup-miniconda@v2
        with:
          installer-url: https://github.com/proppy/conda-eda/releases/download/v0.0-1403-ga3008a5/openlane-gf180mcuc-0-Linux-x86_64.sh
          activate-environment: conda-eda
      - name: build with fusesoc
        shell: bash -l {0}
        run: |
          pip3 install fusesoc
          fusesoc library add serv https://github.com/olofk/serv
          fusesoc library add $REPO $GITHUB_WORKSPACE/$REPO
          fusesoc run --target=gf180 $VLNV
